// =============================================================================
// Render Commands (Platform Agnostic)
// =============================================================================
//
// These commands are generated by the Layouter and consumed by platform-specific
// renderers (Android Canvas, iOS Core Graphics, Web Canvas2D).
// =============================================================================

use crate::bridge::types::{Color, FontSpec, QuantizedRect};

// -----------------------------------------------------------------------------
// Render Command Types
// -----------------------------------------------------------------------------

/// Render command type discriminator
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum RenderCommandType {
    DrawText = 0,
    FillRect = 1,
    DrawLine = 2,
    DrawImage = 3,
}

/// Single render command
///
/// Uses #[repr(C)] for FFI compatibility.
/// Commands are stored in a contiguous buffer for cache efficiency.
#[repr(C)]
#[derive(Clone, Copy)]
pub struct RenderCommand {
    /// Command type
    pub cmd_type: RenderCommandType,
    /// Position and size
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
    /// Color (for all command types)
    pub color: Color,
    /// Union data (interpreted based on cmd_type)
    pub data: RenderCommandData,
}

/// Command-specific data (24 bytes = 3 x u64)
#[repr(C)]
#[derive(Clone, Copy)]
pub union RenderCommandData {
    /// For DrawText: text pointer, length, font spec
    pub text: TextData,
    /// For DrawLine: line data
    pub line: LineData,
    /// For DrawImage: image data
    pub image: ImageData,
    /// Raw bytes for other uses
    pub raw: [u8; 24],
}

unsafe impl Send for RenderCommandData {}
unsafe impl Sync for RenderCommandData {}

// -----------------------------------------------------------------------------
// Text Command Data
// -----------------------------------------------------------------------------

#[repr(C)]
#[derive(Clone, Copy)]
pub struct TextData {
    /// UTF-8 text pointer (owned by renderer)
    pub text_ptr: u64,
    /// Text length in bytes
    pub text_len: u32,
    /// Padding
    pub _pad: u32,
    /// Font specification (16 bytes)
    pub font: FontSpecData,
}

#[repr(C)]
#[derive(Clone, Copy)]
pub struct FontSpecData {
    pub family: u8,      // FontFamily enum
    pub size_pt: u8,     // Size in points (0-255, limited range)
    pub bold: u8,
    pub italic: u8,
    pub _pad: [u8; 12],
}

impl From<FontSpec> for FontSpecData {
    fn from(spec: FontSpec) -> Self {
        Self {
            family: spec.family as u8,
            size_pt: spec.size_pt as u8,
            bold: spec.bold as u8,
            italic: spec.italic as u8,
            _pad: [0; 12],
        }
    }
}

// -----------------------------------------------------------------------------
// Line Command Data
// -----------------------------------------------------------------------------

#[repr(C)]
#[derive(Clone, Copy)]
pub struct LineData {
    /// Line width in pixels
    pub width: f32,
    /// Start coordinates (x1, y1)
    pub x1: f32,
    pub y1: f32,
    /// End coordinates (x2, y2)
    pub x2: f32,
    pub y2: f32,
}

// -----------------------------------------------------------------------------
// Image Command Data
// -----------------------------------------------------------------------------

#[repr(C)]
#[derive(Clone, Copy)]
pub struct ImageData {
    /// Image data pointer
    pub data_ptr: u64,
    /// Data length
    pub data_len: u32,
    pub _pad: u32,
    /// Image format (0 = PNG, 1 = JPEG, 2 = RGBA)
    pub format: u32,
}

// -----------------------------------------------------------------------------
// Render Result (Bundle with Dirty Rects)
// -----------------------------------------------------------------------------

/// Result of a render operation
///
/// Contains render commands and dirty rectangles for partial refresh.
#[repr(C)]
#[derive(Clone)]
pub struct RenderResult {
    /// Render commands
    pub commands: Vec<RenderCommand>,
    /// Dirty rectangles (for partial refresh optimization)
    pub dirty_rects: Vec<QuantizedRect>,
    /// Total document height (for scroll bar calculation)
    pub total_height: f32,
}

impl RenderResult {
    pub fn new() -> Self {
        Self {
            commands: Vec::new(),
            dirty_rects: Vec::new(),
            total_height: 0.0,
        }
    }

    /// Add a command and mark its area as dirty
    pub fn push(&mut self, cmd: RenderCommand) {
        let rect = QuantizedRect::from_float(cmd.x, cmd.y, cmd.width, cmd.height);
        self.dirty_rects.push(rect);
        self.commands.push(cmd);
    }

    /// Merge dirty rectangles to reduce refresh calls
    pub fn merge_dirty_rects(&mut self) {
        if self.dirty_rects.len() <= 1 {
            return;
        }

        let mut merged = Vec::new();
        let mut current = self.dirty_rects[0];

        for &rect in &self.dirty_rects[1..] {
            if current.intersects(&rect) || rect.adjacent_to(&current) {
                current = current.union(&rect);
            } else {
                merged.push(current);
                current = rect;
            }
        }
        merged.push(current);

        self.dirty_rects = merged;
    }

    /// Calculate total dirty area (for deciding global vs partial refresh)
    pub fn total_dirty_area(&self) -> u32 {
        self.dirty_rects.iter().map(|r| r.area()).sum()
    }
}

impl QuantizedRect {
    /// Check if two rectangles are adjacent (touching or within 4 pixels)
    fn adjacent_to(&self, other: &Self) -> bool {
        const GAP: i16 = 4;
        let dx = (self.x as i16 - other.x as i16).abs();
        let dy = (self.y as i16 - other.y as i16).abs();
        dx <= GAP || dy <= GAP
    }
}

// -----------------------------------------------------------------------------
// Command Builders
// -----------------------------------------------------------------------------

impl RenderCommand {
    /// Create a DrawText command
    pub fn draw_text(x: f32, y: f32, text: &str, font: FontSpec, color: Color) -> Self {
        Self {
            cmd_type: RenderCommandType::DrawText,
            x,
            y,
            width: 0.0,  // Will be computed by layouter
            height: 0.0,
            color,
            data: RenderCommandData {
                text: TextData {
                    text_ptr: 0,  // Set by renderer
                    text_len: text.len() as u32,
                    _pad: 0,
                    font: FontSpecData::from(font),
                },
            },
        }
    }

    /// Create a FillRect command
    pub fn fill_rect(x: f32, y: f32, width: f32, height: f32, color: Color) -> Self {
        Self {
            cmd_type: RenderCommandType::FillRect,
            x, y, width, height,
            color,
            data: RenderCommandData { raw: [0; 24] },
        }
    }

    /// Create a DrawLine command
    pub fn draw_line(x1: f32, y1: f32, x2: f32, y2: f32, width: f32, color: Color) -> Self {
        Self {
            cmd_type: RenderCommandType::DrawLine,
            x: x1.min(x2),
            y: y1.min(y2),
            width: (x2 - x1).abs() + width,
            height: (y2 - y1).abs() + width,
            color,
            data: RenderCommandData {
                line: LineData { x1, y1, x2, y2, width },
            },
        }
    }

    /// Create a DrawImage command
    pub fn draw_image(x: f32, y: f32, width: f32, height: f32, data_ptr: u64, data_len: u32, format: u32) -> Self {
        Self {
            cmd_type: RenderCommandType::DrawImage,
            x, y, width, height,
            color: Color::WHITE,
            data: RenderCommandData {
                image: ImageData { data_ptr, data_len, _pad: 0, format },
            },
        }
    }
}

// -----------------------------------------------------------------------------
// FFI Helpers
// ----------------------------------------------------------------------------/

/// Convert commands to FFI-compatible array
///
/// Returns (ptr, len) tuple for passing across FFI boundary.
pub fn commands_to_ffi(commands: &mut Vec<RenderCommand>) -> (*const RenderCommand, usize) {
    (commands.as_ptr(), commands.len())
}

/// Convert dirty rects to FFI-compatible flat array
///
/// Returns [x, y, w, h, x, y, w, h, ...] as [i32; 4 * n]
pub fn dirty_rects_to_ffi(rects: &[QuantizedRect]) -> Vec<i32> {
    let mut result = Vec::with_capacity(rects.len() * 4);
    for rect in rects {
        result.push(rect.x as i32);
        result.push(rect.y as i32);
        result.push(rect.width as i32);
        result.push(rect.height as i32);
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::bridge::types::FontFamily;

    #[test]
    fn test_render_command_draw_text() {
        let cmd = RenderCommand::draw_text(
            10.0, 20.0, "Hello", FontSpec {
                family: FontFamily::Sans,
                size_pt: 14.0,
                bold: false,
                italic: false,
            },
            Color::BLACK
        );

        assert_eq!(cmd.cmd_type, RenderCommandType::DrawText);
        assert_eq!(cmd.x, 10.0);
        assert_eq!(cmd.y, 20.0);
    }

    #[test]
    fn test_render_command_fill_rect() {
        let cmd = RenderCommand::fill_rect(5.0, 10.0, 100.0, 200.0, Color::WHITE);

        assert_eq!(cmd.cmd_type, RenderCommandType::FillRect);
        assert_eq!(cmd.width, 100.0);
        assert_eq!(cmd.height, 200.0);
    }

    #[test]
    fn test_dirty_rects_to_ffi() {
        let rects = vec![
            QuantizedRect { x: 10, y: 20, width: 100, height: 200 },
            QuantizedRect { x: 5, y: 15, width: 50, height: 100 },
        ];

        let ffi = dirty_rects_to_ffi(&rects);
        assert_eq!(ffi.len(), 8);
        assert_eq!(ffi[0], 10);
        assert_eq!(ffi[1], 20);
        assert_eq!(ffi[2], 100);
        assert_eq!(ffi[3], 200);
    }
}
